POST http://localhost:1337/Usuario
Content-Type: application/x-www-form-urlencoded

username=ema&password=1234&email=ema.chiletti@gmail.com

###

POST http://localhost:1337/Campo
Content-Type: application/x-www-form-urlencoded

Nombre=Campo Tcha&CantHas=200&Localidad=Tancacha&Provincia=Cordoba
